Level_Five/learning_users/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

#TEMPLATE TAGS
app_name = 'basicapp'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login' ),
]

Level_Five/learning_users/learning_users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basicapp/', include('basicapp.urls') ),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special'),
]

Level_Five/learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE) #This is what should be done to extend

    #adittional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

Level_Five/learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

Level_Five/learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basicapp/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in! Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.erros, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basicapp/registration.html', context={'user_form':user_form,
                                            'profile_form':profile_form,
                                            'registered':registered} )

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone login and failed!")
            print("Username: {} and password {}" .format(username, password))
            return HttpResponse("invalid login")
    else:
        return render(request, 'basicapp/login.html', {}) #Empty Context

Level_Five/learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">Django </a></li>
          <li class="nav-item"><a class="navbar-link" href="{% url 'admin:index' %}">Admin </a></li>
          <li class="nav-item"><a class="navbar-link" href="{% url 'basicapp:register' %}">Register </a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
            <p>Hello, {{user.get_username}}</p>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
          {% endif %}



        </ul>
      </div>

    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>


  </body>
</html>

Level_Five/learning_users/templates/basicapp/index.html
{% extends 'basicapp/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock %}

Level_Five/learning_users/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Pleas, Login</h1>
  <form action="{% url 'basicapp:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">UserName:</label>
    <input type="text" name="username" value="Enter UserName">

    <label for="passowrd">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>

</div>

{% endblock %}

Level_Five/learning_users/templates/basicapp/registration.html
{% extends 'basicapp/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>Thanks for registering!</h1>
  {% else %}
    <h1>Register Here</h1>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}

</div>

{% endblock %}