Level_Four/projfour/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('other/', views.other, name='other'),
]

Level_Four/projfour/projfour/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/', include('basicapp.urls')),
]

Level_Four/projfour/basicapp/models.py
from django.db import models

# Create your models here.

Level_Four/projfour/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    text = 'this text was all written in small caps, but you are seeing this as title'
    ano = 1984
    return render(request, 'basicapp/index.html', context={'texto':text, 'birth':ano})

def other(request):
    return render(request, 'basicapp/other.html')

Level_Four/projfour/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>The Page of Blabla</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}

      </div>

    </div>
  </body>
</html>

Level_Four/projfour/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}

{% load calculo_idade %}
      <h1>This is the index page</h1>
      <p> {{ texto|title }} </p>
      <p>My year of birth: {{ birth }}</p>
      <p>My age is: {{ birth|calcula_a_idade:'ok' }}</p>
      <a href="{% url 'basicapp:other' %}">This one goes to other.html</a>
{% endblock %}

Level_Four/projfour/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
      <h1>This is the Other html</h1>
      <a href="{% url 'basicapp:index' %}">This one goes to basicapp/index</a>
      <br>
      <a href="{% url 'index' %}">This one goes back to real index</a>
      <br>
      <a href="{% url 'admin:index' %}">This one goes to admin page</a>
{% endblock %}